import { Inter } from "next/font/google";
import Navbar from './components/navbar';
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="{inter.className} bg-[#00051e]">
      <div className="w-[100vw] h-[100vh] box-border">
          <Navbar />
        {children}
      </div>
        </body>
    </html>
  );
}
